BRAILLE.obj \
BRAILLE.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH FOAM.GOH MAILBOX.GOH COMMON.GOH
BRAILLE.obj \
BRAILLE.eobj: BRAILLE.GOC GEOS.H C:/PCGEOS/LOCAL/BCC/INCLUDE/STDDEF.H \
                C:/PCGEOS/LOCAL/BCC/INCLUDE/_DEFS.H \
                C:/PCGEOS/LOCAL/BCC/INCLUDE/_NULL.H HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H UDIALOG.H OBJECTS/GINTERC.H WIN.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H MEDIUM.H ANSI/STDIO.H \
                C:/PCGEOS/LOCAL/BCC/INCLUDE/STDARG.H ANSI/STRING.H \
                VOICE.H BRAILLE.H STREAMC.H
BRAIL_AL.obj \
BRAIL_AL.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH FOAM.GOH MAILBOX.GOH COMMON.GOH
BRAIL_AL.obj \
BRAIL_AL.eobj: BRAIL_AL.GOC GEOS.H C:/PCGEOS/LOCAL/BCC/INCLUDE/STDDEF.H \
                C:/PCGEOS/LOCAL/BCC/INCLUDE/_DEFS.H \
                C:/PCGEOS/LOCAL/BCC/INCLUDE/_NULL.H HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H UDIALOG.H OBJECTS/GINTERC.H WIN.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H MEDIUM.H STREAMC.H ANSI/STDIO.H \
                C:/PCGEOS/LOCAL/BCC/INCLUDE/STDARG.H ANSI/STRING.H \
                VOICE.H BRAILLE.H MACROENG.H BRAIL_AL.H
BRAIL_HT.obj \
BRAIL_HT.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH FOAM.GOH MAILBOX.GOH COMMON.GOH
BRAIL_HT.obj \
BRAIL_HT.eobj: BRAIL_HT.GOC GEOS.H C:/PCGEOS/LOCAL/BCC/INCLUDE/STDDEF.H \
                C:/PCGEOS/LOCAL/BCC/INCLUDE/_DEFS.H \
                C:/PCGEOS/LOCAL/BCC/INCLUDE/_NULL.H HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H UDIALOG.H OBJECTS/GINTERC.H WIN.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H MEDIUM.H STREAMC.H ANSI/STDIO.H \
                C:/PCGEOS/LOCAL/BCC/INCLUDE/STDARG.H ANSI/STRING.H \
                VOICE.H BRAILLE.H MACROENG.H BRAIL_HT.H
OBJID.obj \
OBJID.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH FOAM.GOH MAILBOX.GOH COMMON.GOH
OBJID.obj \
OBJID.eobj: OBJID.GOC GEOS.H C:/PCGEOS/LOCAL/BCC/INCLUDE/STDDEF.H \
                C:/PCGEOS/LOCAL/BCC/INCLUDE/_DEFS.H \
                C:/PCGEOS/LOCAL/BCC/INCLUDE/_NULL.H HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H UDIALOG.H OBJECTS/GINTERC.H WIN.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H MEDIUM.H ANSI/STDIO.H \
                C:/PCGEOS/LOCAL/BCC/INCLUDE/STDARG.H ANSI/STRING.H \
                VOICE.H BRAILLE.H STREAMC.H
SPEAK.obj \
SPEAK.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH FOAM.GOH MAILBOX.GOH \
                INTERNAL/RESPONDR.GOH INTERNAL/RESP/ECI.GOH \
                INTERNAL/RESP/SMDEFINE.GOH INTERNAL/RESP/INDICATO.GOH \
                COMMON.GOH SPEAK_UI.GOH
SPEAK.obj \
SPEAK.eobj: SPEAK.GOC GEOS.H C:/PCGEOS/LOCAL/BCC/INCLUDE/STDDEF.H \
                C:/PCGEOS/LOCAL/BCC/INCLUDE/_DEFS.H \
                C:/PCGEOS/LOCAL/BCC/INCLUDE/_NULL.H HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H UDIALOG.H OBJECTS/GINTERC.H WIN.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H MEDIUM.H INITFILE.H ANSI/STDIO.H \
                C:/PCGEOS/LOCAL/BCC/INCLUDE/STDARG.H ANSI/STDLIB.H \
                ANSI/STRING.H VOICE.H BRAILLE.H STREAMC.H MACROENG.H \
                ./SERIAL.INC
SYNTH.obj \
SYNTH.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH FOAM.GOH MAILBOX.GOH \
                INTERNAL/RESP/VRECUI.GOH INTERNAL/RESP/INDICATO.GOH \
                INTERNAL/RESPONDR.GOH SECURITY.GOH COMMON.GOH
SYNTH.obj \
SYNTH.eobj: SYNTH.GOC GEOS.H C:/PCGEOS/LOCAL/BCC/INCLUDE/STDDEF.H \
                C:/PCGEOS/LOCAL/BCC/INCLUDE/_DEFS.H \
                C:/PCGEOS/LOCAL/BCC/INCLUDE/_NULL.H HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H UDIALOG.H OBJECTS/GINTERC.H WIN.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H MEDIUM.H STREAMC.H ANSI/STDIO.H \
                C:/PCGEOS/LOCAL/BCC/INCLUDE/STDARG.H ANSI/STRING.H \
                VOICE.H BRAILLE.H
GSPARSE.obj \
GSPARSE.eobj: GEOS.DEF RESOURCE.DEF GSTRING.DEF GRAPHICS.DEF FONTID.DEF \
                FONT.DEF COLOR.DEF TEXT.DEF CHAR.DEF
MACROENG.obj \
MACROENG.eobj: STDAPP.DEF GEOS.DEF GEODE.DEF RESOURCE.DEF EC.DEF LMEM.DEF \
                OBJECT.DEF GRAPHICS.DEF FONTID.DEF FONT.DEF COLOR.DEF \
                GSTRING.DEF TEXT.DEF CHAR.DEF HEAP.DEF UI.DEF FILE.DEF \
                VM.DEF WIN.DEF INPUT.DEF LOCALIZE.DEF SLLANG.DEF \
                OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF CHUNKARR.DEF \
                GEOWORKS.DEF GCNLIST.DEF OBJECTS/TEXT/TCOMMON.DEF \
                STYLESH.DEF IACP.DEF OBJECTS/UIINPUTC.DEF \
                OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF OBJECTS/VCNTC.DEF \
                INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF DISK.DEF DRIVE.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF HWR.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                TIMER.DEF THREAD.DEF OBJECTS/INPUTC.DEF INTERNAL/IM.DEF \
                INTERNAL/SEMINT.DEF MACROENG.DEF

speakEC.geo speak.geo : GEOS.LDF UI.LDF ANSIC.LDF TEXT.LDF STREAMC.LDF ECI.LDF FOAM.LDF VRECUI.LDF SECURITY.LDF RESPONDR.LDF 